### ISSUE TITLE
Why is Eq and PartialEq not implemented?

### ISSUE THREAD

**Issue by pYtoner** [xacrimon/dashmap#138]
Couldn't it be implemented similarl to how hashbrown does it?

Wouldn't something like this work?
```
impl<K, V, S> PartialEq for DashMap<K, V, S>
where
    K: Send + Sync + Eq + Hash,
    V: Send + Sync + PartialEq,
    S: Send + Sync + Clone + BuildHasher,
{
    fn eq(&self, other: &Self) -> bool {
        if self.len() != other.len() {
            return false;
        }

        self.iter().all(|r| {
            other
                .get(r.key())
                .map_or(false, |r2| r.value() == r2.value())
        });
    }
}

impl<K, V, S> Eq for DashMap<K, V, S>
where
    K: Send + Sync + Eq + Hash,
    V: Send + Sync + Eq,
    S: Send + Sync + Clone + BuildHasher,
{
}
```

**Comment by xacrimon** [comment]
They aren't implemented because equality makes no sense for a concurrent map. Fundamentally you never really have to compare two and if you do, you're probably architecting your code in a non-optimal way. Concurrent maps are typically long lived and almost all operations should operate on one or a few keys and not iterate, they're also typically quite large in terms of element count.
