### ISSUE TITLE
Unable to use the result of `get()` in a method.

### ISSUE THREAD

**Issue by kritika-gupta** [xacrimon/dashmap#140]
I am using dashmaps for a use case with nested maps. An outer dashmap has values that are also dashmaps. I am trying to write a method for the outer map to retrieve a value in the inner map (by passing it an outer key and inner key). The method essentially chains the `get()` methods of both the maps. I have included a sample toy code that tries to achieve this (I have removed the actual surrounding business logic for clarity).
```rust
use dashmap::DashMap;
use std::collections::hash_map::RandomState;
use dashmap::mapref::one::Ref;

struct OuterMap {
    maps: DashMap<i32, InnerMap>
}
impl OuterMap {
    fn new(num_maps: i32) -> Self {
        let maps = DashMap::new();
        (0..num_maps).for_each(|i| {
            maps.insert(i, InnerMap::new());
        });
        Self { maps }
    }
    fn get_inner_value(&self, outer_key: i32, inner_key: i32) -> Option<Ref<i32, i32, RandomState>> {
        self.maps.get(&outer_key).unwrap().get(&inner_key)
    }
}

struct InnerMap {
    map: DashMap<i32, i32>
}
impl InnerMap {
    fn new() -> Self {
        let map = DashMap::new();
        (0..10).for_each(|x| {
            map.insert(x, x);
        });
        Self { map }
    }
    fn get(&self, key: &i32) -> Option<Ref<i32, i32, RandomState>> {
        self.map.get(key)
    }
}

fn main() {
    let outer_map = OuterMap::new(4);
    let result = outer_map.get_inner_value(0, 0);
    println!("Value at 0th key of 0th map: {}", result.unwrap().value())
}
```

```zsh
error[E0515]: cannot return value referencing temporary value
  --> src/bin/dashmap_get.rs:17:9
   |
17 |         self.maps.get(&outer_key).unwrap().get(&inner_key)
   |         ----------------------------------^^^^^^^^^^^^^^^^
   |         |
   |         returns a value referencing data owned by the current function
   |         temporary value created here

error: aborting due to previous error
```

This works perfectly when the maps are hashmaps but fails with dashmaps. What is the correct way to achieve this?

**Comment by xacrimon** [comment]
This errors because the first get() creates a guard that must be kept alive for the entire duration of the second borrow. Usually nested dash maps indicate non-optimal code architecture and there is probably a better way to accomplish your solution. Dashmap is not a be all and all tool and initialising them is very expensive. I'd advise looking over your code to see if you really want nested dashmaps. That said the solution to your problem is assigning output from the first get to a variable and then calling get on that variable again. This keeps the guard alive.
