### ISSUE TITLE
drain support?

### ISSUE THREAD

**Issue by Enter-tainer** [xacrimon/dashmap#141]
`std::collections::HashMap` includes a method [`drain`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.drain) , which clear the map and allow the allocated memory for reuse, it's really useful to move data around.

Is it possible to add `drain` for dashmap?

**Comment by xacrimon** [comment]
Adding `drain` for dashmap is certainly possible although the consistency guarantees will be very whacky. This is mostly due to the fact that concurrent mutable access is permitted in many cases. IMO if you need drain for dashmap that's usually an XY problem and is better solved by reworking your logic to not use dashmap for short lived maps as that isn't what it was designed for. Initializing dash maps is very expensive. If you provide your specific use-case I may be able to suggest a better way to accomplish what you're doing. IMHO including drain opens up a lot of room for confusion and traps as it may behave differently in comparison to their expectation coming from non-concurrent types.

**Comment by Enter-tainer** [comment]
Thanks for your reply! And I've come up with a better idea without using drain.
