### ISSUE TITLE
Performance regression from 3.11.10 to 4.0.2

### ISSUE THREAD

**Issue by ahornby** [xacrimon/dashmap#144]
Hi,  in https://github.com/droundy/internment/pull/26  I upgraded internments dashmap dependency from 3.x line to 4.x, and despite some confounding variation in my test env it looks like 4.0.2 is sometimes twice as slow for the ArcIntern tests.

Theres not a huge amount of code change between 3.10.11 and 4.0.2 so perhaps this is from the switch of depdency from ahash RandomState to std RandomState in https://github.com/xacrimon/dashmap/commit/ef374938a52a19b5c55b53db9ed22d150fc3b5a2.     What was the underlying issue with ahash this was fixing?  If it wasn't a fatal flaw it might be worth trying a revert and rebenchmarking.

**Comment by xacrimon** [comment]
Hi, the default hasher was changed since introducing a mandatory dependency on ahash is not something we want to do. To reclaim this performance, use the existing functionality to use a custom hasher of your choice after careful consideration. ahash has a number of issues preventing it from something we want to pull in my default.

**Comment by ahornby** [comment]
Thanks, makes sense.

**Comment by tkaitchuck** [comment]
> ahash has a number of issues preventing it from something we want to pull in by default.

Can you file issues on these in the aHash repo? It is intended that aHash should work as a sane default.
