### ISSUE TITLE
dashmap loading only one thread

### ISSUE THREAD

**Issue by ratal** [xacrimon/dashmap#184]
Hi, 
Using latest version 5.1
I am noticing performance degradation since I refactored the values held by a dashmap I use in my application. Honestly, I am not 100% sure if this is the root cause. Values are a struct of vec, hashmap and enums. I am trying to modify content in place using rayon feature, mostly processing raw xml text into hashmap.
`pub fn extract_xml(&self) {`
`        self.md_tx          (Arc<DashMap<i64, MetaData>>)`
`            .par_iter_mut()`
`            .filter(|x| x.block_type == MetaDataBlockType::MdBlock)`
`           .for_each(|mut val| val.parse_xml());`
   ` }`
Looking at a simple top, many threads are present but only one loaded.
I tried to force unsafe Sync and Send to my struct but no change
Did I miss something ? Is there a way to debug this behavior ?

**Comment by xacrimon** [comment]
Hi, `dashmap` isn't really target and specialized for iteration workloads. The primary thing we optimize for is point-lookup OLTP-style workloads. This means the internal structure for the map isn't extremely suitable for fast parallel iteration. Usually when people want to iterate over dashmaps, the map is never actually a measurable bottleneck in the application since iteration by nature doesn't mix well with datastructures that update in parallel under the "feet" of the iterator.

**Comment by xacrimon** [comment]
While we could optimize this further in the future with another design. The current backing implementation isn't designed for this type of workload.

**Comment by ratal** [comment]
Thanks xacrimon
Understood, in the mean time I will try to find an alternative in my design to parallelize this workload.
Closing
