### ISSUE TITLE
Use len within or_insert_with?

### ISSUE THREAD

**Issue by sehkone** [xacrimon/dashmap#35]
In the 1.x, the below worked well.

```
map.get_or_insert(&key, map.len() + 1)
```

But, in later versions, both 2.x and 3.x, the below just halts.

```
map.entry(key).or_insert_with(|| map.len() + 1)
```

Can you give me any ideas to resolve this issue?

**Comment by xacrimon** [comment]
Ah yes, it's because the previous version eagerly precalculated it and could drop the value. So here you end up grabbing an entry lock and then again in your closure. Solve this by precalculcating map.len() + 1 on the line before.

**Comment by sehkone** [comment]
Thank you for your answer. But, I want to make it sure that the length of map doesn't change between the precalculation and `or_insert_with`.  How can I do that?

**Comment by xacrimon** [comment]
Technically that wasn't the case before either. The length could still change inbetween. If you really must be sure that the length cant change between you will have to sacrifice a lot of performance since you have to lock the map. This is something very hard to do in concurrent datastructures like this one.

Your best bet for implementing this is to enable the `raw-api` feature and use the `shards()` method to get the shards. Once you have them you will need to iterate through them and lock them all and stash the locks in a Vec. Finally you use the `determine_map(&key)` method to find out which shard the key for the length entry will go into and insert it into the correct shard based on the index of its lock within your vector of locks.

**Comment by sehkone** [comment]
I will consider what you've explained. Thank you so much again.
