### ISSUE TITLE
Blocking after get_mut when reaccessing key

### ISSUE THREAD

**Issue by quietvoid** [xacrimon/dashmap#64]
Hi,

This might not be the place for this kind of question.
I'm curious about this behaviour where my program locks up when I reaccess the map using a key that was borrowed as mutable.
My code is here: https://gist.github.com/rust-play/26c34df4f98d5ce6b34e050763092215

In this case, only the first line is printed. After, the program still keeps using a single thread at 100% (and multiple threads when using tokio async).

Is this expected behaviour? Because the compiler does not complain.
If it is, are there ways to achieve what I'm trying to do? Perhaps using shards and awaiting/manually releasing the lock.

Thanks.

**Comment by xacrimon** [comment]
This is an unfortunate reality caused by the current implementation. You can solve this by enabling the `raw-api` feature and using the shards method to get a slice of shards and using determine_map to find the shard for a key and managing the locks manually. This is something I know about and something I am working on fixing. The experimental branch currently holds what will become dashmap v4 which will solve this issue entirely. Thanks for your understanding.
